# Site settings
title: Blanka Cahová
email: bcahova@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blankacahova.com" # the base hostname & protocol for your site
permalink: "projects/:title"

# Build settings
markdown: kramdown
